[workspace]
members = [
  "actors",
  # "gthreads",
  "asyncly",
  "minitokio",
  "myredis",
  "rep",
  "task"
]

# Binary size optimizations
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
debug = true